[envs.defined]
command = "bril2json < {filename} | python3 flow.py defined"
output."defined.out" = "-"

[envs.cprop]
command = "bril2json < {filename} | python3 flow.py cprop"
output."cprop.out" = "-"